services:
  - type: web
    name: technical-design-assistant
    env: python
    buildCommand: pip install --no-build-isolation --prefer-binary -r requirements.txt
    startCommand: gunicorn wsgi:app --workers $WEB_CONCURRENCY --timeout 600 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
